/**
 * Copyright 2017 University of Victoria
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
package com.rigiresearch.examgen.templates;

import com.rigiresearch.examgen.model.Examination;
import com.rigiresearch.examgen.templates.Template;

/**
 * A Latex template implementation.
 * @author Miguel Jimenez (miguel@uvic.ca)
 * @date 2017-09-14
 * @version $Id$
 * @since 0.0.1
 */
@SuppressWarnings("all")
public class LatexQuiz implements Template {
  @Override
  public CharSequence render(final Examination e, final boolean printSolutions) {
    throw new Error("Unresolved compilation problems:"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'«\'"
      + "\nno viable alternative at input \'«\'"
      + "\nmismatched input \'\\\' expecting \'}\'"
      + "\nno viable alternative at input \'footnotesize\'"
      + "\nno viable alternative at input \'This\'"
      + "\nno viable alternative at input \'exam\'"
      + "\nno viable alternative at input \'is\'"
      + "\nno viable alternative at input \'worth\'"
      + "\nno viable alternative at input \'a\'"
      + "\nno viable alternative at input \'total\'"
      + "\nno viable alternative at input \'of\'"
      + "\nno viable alternative at input \'numpoints\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'marks\'"
      + "\nno viable alternative at input \'and\'"
      + "\nno viable alternative at input \'contains\'"
      + "\nno viable alternative at input \'numquestions\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'questions\'"
      + "\nno viable alternative at input \'on\'"
      + "\nno viable alternative at input \'numpages\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'pages\'"
      + "\nno viable alternative at input \'}\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'\\\'"
      + "\nno viable alternative at input \'begin\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'\\\'"
      + "\nno viable alternative at input \'bracketedpoints\'"
      + "\nno viable alternative at input \'marksnotpoints\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'FOR\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'»\\r\\n        \\end{questions}\\r\\n        \\end{document}\\r\\n    \'\'\'\'"
      + "\nno viable alternative at input \'override\'"
      + "\nmissing \')\' at \'question\'"
      + "\nno viable alternative at input \',\'"
      + "\nno viable alternative at input \'printSolutions\'"
      + "\nno viable alternative at input \')\'"
      + "\nno viable alternative at input \'override\'"
      + "\nno viable alternative at input \'render\'"
      + "\nextraneous input \'segment\' expecting \')\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'def\'"
      + "\nno viable alternative at input \'styled\'"
      + "\nextraneous input \'segment\' expecting \')\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'def\'"
      + "\nno viable alternative at input \'styled\'"
      + "\nmissing \')\' at \'text\'"
      + "\nno viable alternative at input \',\'"
      + "\nno viable alternative at input \'style\'"
      + "\nno viable alternative at input \')\'"
      + "\nno viable alternative at input \'def\'"
      + "\nno viable alternative at input \'escaped\'"
      + "\nextraneous input \'text\' expecting \')\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'def\'"
      + "\nno viable alternative at input \'scapedInline\'"
      + "\nextraneous input \'text\' expecting \')\'"
      + "\nno viable alternative at input \'{\'"
      + "\nno viable alternative at input \'def\'"
      + "\nno viable alternative at input \'render\'"
      + "\nmissing \')\' at \'question\'"
      + "\nno viable alternative at input \',\'"
      + "\nno viable alternative at input \'child\'"
      + "\nno viable alternative at input \',\'"
      + "\nno viable alternative at input \'printSolutions\'"
      + "\nno viable alternative at input \')\'"
      + "\nno viable alternative at input \'»\\r\\n    \'\'\'\'"
      + "\nno viable alternative at input \'def\'"
      + "\nmissing \')\' at \'question\'"
      + "\nno viable alternative at input \',\'"
      + "\nno viable alternative at input \'child\'"
      + "\nno viable alternative at input \',\'"
      + "\nno viable alternative at input \'printSolutions\'"
      + "\nno viable alternative at input \')\'"
      + "\nno viable alternative at input \'»\\r\\n        \\end{items}\\r\\n    \'\'\'\'"
      + "\nno viable alternative at input \'def\'"
      + "\nmissing \')\' at \'question\'"
      + "\nno viable alternative at input \',\'"
      + "\nno viable alternative at input \'child\'"
      + "\nno viable alternative at input \',\'"
      + "\nno viable alternative at input \'printSolutions\'"
      + "\nno viable alternative at input \')\'"
      + "\nno viable alternative at input \'»}\\r\\n    \'\'\'\'"
      + "\nno viable alternative at input \'def\'"
      + "\nmissing \')\' at \'question\'"
      + "\nno viable alternative at input \',\'"
      + "\nno viable alternative at input \'printSolutions\'"
      + "\nno viable alternative at input \')\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'Â\'"
      + "\nno viable alternative at input \'»\\r\\n        \\end{parts}\\r\\n        \\nopointsinmargin\\pointformat{[\\thepoints]} % activate points again\\r\\n        \\addpoints\\r\\n    \'\'\'\'"
      + "\nno viable alternative at input \'def\'"
      + "\nno viable alternative at input \'packages\'"
      + "\nno viable alternative at input \'\'\'\'\\r\\n    % general\\r\\n    \\usepackage[utf8]{inputenc}\\r\\n    \\usepackage[margin=0.5in]{geometry}\\r\\n    % math\\r\\n    \\usepackage{amsmath, amssymb}\\r\\n    % tables\\r\\n    \\usepackage{tabularx}\\r\\n    \\usepackage{multicol}\\r\\n    % listings\\r\\n    \\usepackage{color}\\r\\n    \\usepackage[scaled=0.85]{sourcecodepro}\\r\\n    \\usepackage{listings}\\r\\n    \\usepackage{upquote}\\r\\n    % horizontal list of options\\r\\n    \\usepackage{environ}\\r\\n    \\usepackage[normalem]{ulem}\\r\\n    \\usepackage{etoolbox}\\r\\n    \\usepackage[export]{adjustbox}\\r\\n    \\usepackage{enumitem}\\r\\n    \'\'\'\'"
      + "\nno viable alternative at input \'def\'"
      + "\nno viable alternative at input \'listings\'"
      + "\nno viable alternative at input \'\'\'\'\\r\\n    \\definecolor{keywords}{RGB}{127,0,85}\\r\\n    \\definecolor{comments}{RGB}{63,127,95}\\r\\n    \\definecolor{strings}{RGB}{42,0,255}\\r\\n    \\definecolor{frame}{RGB}{150,150,150}\\r\\n    \\definecolor{numbers}{RGB}{100,100,100}\\r\\n    \\lstdefinestyle{code}{\\r\\n        language=C,\\r\\n        tabsize=4,\\r\\n        captionpos=b,\\r\\n        showspaces=false,\\r\\n        showtabs=false,\\r\\n        breaklines=true,\\r\\n        showstringspaces=false,\\r\\n        breakatwhitespace=true,\\r\\n        escapeinside={(*@}{@*)},\\r\\n        commentstyle=\\color{comments},\\r\\n        keywordstyle=\\bfseries\\color{keywords},\\r\\n        stringstyle=\\color{strings},\\r\\n        basicstyle=\\small\\ttfamily,\\r\\n        frame=lines,\\r\\n        rulecolor=\\color{frame},\\r\\n        xleftmargin=2em,\\r\\n        framexleftmargin=1.5em,\\r\\n        numbers=left,\\r\\n        numbersep=10pt,\\r\\n        numberstyle=\\scriptsize\\ttfamily\\color{numbers}\\r\\n    }\\r\\n    \\lstset{style=code}\\r\\n    \'\'\'\'"
      + "\nno viable alternative at input \'def\'"
      + "\nno viable alternative at input \'trueFalse\'"
      + "\nno viable alternative at input \'\'\'\'\\r\\n    \\newcommand*{\\TrueFalse}[1]{%\\r\\n    \\ifprintanswers\\r\\n        \\ifthenelse{\\equal{#1}{T}}{%\\r\\n            \\textbf{TRUE}\\hspace*{14pt}False\\r\\n        }{\\r\\n            True\\hspace*{14pt}\\textbf{FALSE}\\r\\n        }\\r\\n    \\else\\r\\n        {True}\\hspace*{20pt}False\\r\\n    \\fi\\r\\n    } \\r\\n    %% The following code is based on an answer by Gonzalo Medina\\r\\n    %% https://tex.stackexchange.com/a/13106/39194\\r\\n    \\newlength\\TFlengthA\\r\\n    \\newlength\\TFlengthB\\r\\n    \\settowidth\\TFlengthA{\\hspace*{1.16in}}\\r\\n    \\newcommand\\TFQuestion[2]{%\\r\\n        \\setlength\\TFlengthB{\\linewidth}\\r\\n        \\addtolength\\TFlengthB{-\\TFlengthA}\\r\\n        \\parbox[t]{\\TFlengthA}{\\TrueFalse{#1}}\\parbox[t]{\\TFlengthB}{#2}}\\r\\n    \'\'\'\'"
      + "\nno viable alternative at input \'def\'"
      + "\nno viable alternative at input \'choices\'"
      + "\nno viable alternative at input \'\'\'\'\\r\\n    \\renewcommand{\\questionshook}{%\\r\\n        \\setlength{\\itemsep}{0.5\\baselineskip}\\r\\n        \\setlength{\\topsep}{0pt}\\r\\n        \\setlength\\partopsep{0pt} \\r\\n        \\setlength\\parsep{5pt}\\r\\n    }\\r\\n    \\r\\n    \\makeatletter\\r\\n    \\newlength\\choiceitemwidth\\r\\n    \\newif\\ifshowsolution \\showsolutiontrue\\r\\n    \\newcounter{choiceitem}%\\r\\n    \\r\\n    \\def\\thechoiceitem{\\Alph{choiceitem}}%\\r\\n    \\setlength{\\fboxsep}{0pt}\\r\\n    \\def\\makechoicelabel#1{#1\\uline{\\bfseries \\thechoiceitem.}\\else\\thechoiceitem.\\fi\\space}\\r\\n    %\\def\\makechoicelabel#1{#1\\uline{\\thechoiceitem.}\\else\\thechoiceitem.\\fi\\space} %underline the answer item label if we want to print the answer\\r\\n    %\\def\\makechoicelabel#1{#1\\framebox[1.25em][l]{\\thechoiceitem.}\\else\\makebox[1.25em][l]{\\thechoiceitem.}\\fi} %underline the answer item label if we want to print the answer\\r\\n    \\r\\n    \\def\\choice@mesureitem#1{\\cr\\stepcounter{choiceitem}\\makechoicelabel#1}%\\r\\n    \\r\\n    %measure the choices, this is the first time we need to parse the \\BODY\\r\\n    \\def\\choicemesureitem{\\@ifstar\\r\\n        {\\choice@mesureitem\\ifprintanswers \\xappto\\theanswer{\\thechoiceitem}\\ignorespaces}%\\r\\n        {\\choice@mesureitem\\iffalse}}%\\r\\n    \\r\\n    \\def\\choice@blockitem#1{%\\r\\n        \\ifnum\\value{choiceitem}>0\\hfill\\fi\\r\\n        \\egroup\\hskip0pt\\r\\n        \\hbox to \\choiceitemwidth\\bgroup\\hss\\refstepcounter{choiceitem}\\makechoicelabel#1}\\r\\n    \\r\\n    \\def\\choiceblockitem{\\@ifstar\\r\\n        {\\choice@blockitem\\ifprintanswers\\ignorespaces}%\\r\\n        {\\choice@blockitem\\iffalse}}\\r\\n    \\r\\n    \\def\\choice@paraitem#1{%\\r\\n        \\par\\noindent\\refstepcounter{choiceitem}\\makechoicelabel#1\\hangindent=1.25em\\hangafter=1\\relax}% only the first line need indent\\r\\n    \\r\\n    \\def\\choiceparaitem{\\@ifstar\\r\\n        {\\choice@paraitem\\ifprintanswers\\ignorespaces}%\\r\\n        {\\choice@paraitem\\iffalse}}\\r\\n    \\r\\n    \\newdimen\\qanswd\\r\\n    \\newdimen\\qanswdtmp\\r\\n    \\newbox\\qimgbox\\r\\n    \\NewEnviron{items}[1][]{%\\r\\n        \\def\\theanswer{}\\r\\n        \\begingroup\\r\\n        \\let\\item\\choicemesureitem\\r\\n        \\setcounter{choiceitem}{0}%\\r\\n        \\settowidth{\\global\\choiceitemwidth}{\\vbox{\\halign{##\\hfil\\cr\\BODY\\crcr}}}%\\r\\n        \\endgroup\\r\\n        \\setbox\\qimgbox\\hbox{#1}%\\r\\n        \\setlist[trivlist]{nosep}\\r\\n        \\trivlist\\item\\relax%\\r\\n        \\qanswd=\\linewidth%\\r\\n        \\advance\\qanswd-\\wd\\qimgbox%\\r\\n        % handle large images (leaving less than 30% space)\\r\\n        \\qanswdtmp=0.3\\linewidth%\\r\\n        \\ifnum\\qanswd<\\qanswdtmp%\\r\\n        %\\strut\\hfill% uncomment to right-align large images\\r\\n        \\unhbox\\qimgbox%\\r\\n        %\\hfill\\strut% uncomment this too to center them\\r\\n        \\par%\\r\\n        \\qanswd=\\linewidth%\\r\\n        \\setbox\\qimgbox\\hbox{}%\\r\\n        \\fi%\\r\\n        % end of handling for large images\\r\\n        \\begin{minipage}[t]{\\qanswd}\\r\\n            \\trivlist\\item\\relax%\\r\\n            \\parindent0pt%  \\r\\n            \\setcounter{choiceitem}{0}%\\r\\n            \\ifdim\\choiceitemwidth<0.25\\columnwidth\\r\\n            \\choiceitemwidth=0.25\\columnwidth\\r\\n            \\let\\item\\choiceblockitem\\r\\n            \\bgroup\\BODY\\hfill\\egroup\\r\\n            \\else\\ifdim\\choiceitemwidth<0.5\\columnwidth\\r\\n            \\choiceitemwidth=0.5\\columnwidth\\r\\n            \\let\\item\\choiceblockitem\\r\\n            \\bgroup\\BODY\\hfill\\egroup\\r\\n            \\else % \\choiceitemwidth > 0.5\\columnwidth\\r\\n            \\let\\item\\choiceparaitem\\r\\n            \\BODY\\r\\n            \\fi\\fi\\r\\n            \\endtrivlist\\r\\n        \\end{minipage}%\\r\\n        \\adjustbox{valign=t}{\\unhbox\\qimgbox}\\r\\n        \\endtrivlist\\r\\n    }\\r\\n    \\makeatother\\r\\n    \'\'\'\'"
      + "\nno viable alternative at input \'}\'"
      + "\nSectionÂ cannot be resolved to a type."
      + "\nThe method or field printSolutionsÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field packagesÂ is undefined"
      + "\nThe method or field choicesÂ is undefined"
      + "\nThe method or field trueFalseÂ is undefined"
      + "\nThe method or field listingsÂ is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field footnotesize is undefined"
      + "\nThe method or field This is undefined"
      + "\nThe method or field exam is undefined"
      + "\nThe method or field is is undefined"
      + "\nThe method or field worth is undefined"
      + "\nThe method or field a is undefined"
      + "\nThe method or field total is undefined"
      + "\nThe method or field numpoints is undefined"
      + "\nThe method or field marks is undefined"
      + "\nThe method or field and is undefined"
      + "\nThe method or field numquestions is undefined"
      + "\nThe method or field questions is undefined"
      + "\nThe method or field numpages is undefined"
      + "\nThe method or field pages is undefined"
      + "\nThe method or field vspace is undefined"
      + "\nThe method or field cm is undefined"
      + "\nThe method or field begin is undefined"
      + "\nThe method or field questions is undefined"
      + "\nThe method or field marksnotpoints is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field override is undefined"
      + "\nThe method or field segment is undefined"
      + "\nThe method or field segment is undefined"
      + "\nThe method or field segment is undefined"
      + "\nThe method or field styled is undefined for the type Object"
      + "\nThe method or field def is undefined"
      + "\nThe method styled(Class<TextSegment>) is undefined"
      + "\nThe method or field segment is undefined"
      + "\nThe method or field segment is undefined"
      + "\nThe method styled(Object) is undefined for the type CharSequence"
      + "\nThe method or field segment is undefined"
      + "\nThe method or field def is undefined"
      + "\nThe method styled(Class<CharSequence>) is undefined"
      + "\nThe method or field text is undefined"
      + "\nThe method or field style is undefined"
      + "\nThe method or field style is undefined"
      + "\nThe method or field BOLD is undefined"
      + "\nThe method or field text is undefined"
      + "\nThe method or field CODE is undefined"
      + "\nThe method or field textÂ is undefined"
      + "\nThe method or field INLINE_CODE is undefined"
      + "\nThe method or field text is undefined"
      + "\nThe method or field ITALIC is undefined"
      + "\nThe method or field text is undefined"
      + "\nThe method or field CUSTOM is undefined"
      + "\nThe method or field text is undefined"
      + "\nThe method or field INHERIT is undefined"
      + "\nThe method or field text is undefined"
      + "\nThe method or field NEW_LINE is undefined"
      + "\nThe method or field text is undefined"
      + "\nThe method or field def is undefined"
      + "\nThe method escaped(Class<CharSequence>) is undefined"
      + "\nThe method or field text is undefined"
      + "\nThe method or field def is undefined"
      + "\nThe method scapedInline(Class<CharSequence>) is undefined"
      + "\nThe method or field text is undefined"
      + "\nThe method or field def is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field child is undefined"
      + "\nThe method or field childÂ is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field printSolutionsÂ is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field ELSEÂ is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field child is undefined"
      + "\nThe method or field childÂ is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field ELSEÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field child is undefined"
      + "\nThe method or field childÂ is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field ELSEÂ is undefined"
      + "\nThe method or field ENDIFÂ is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field question is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field Â is undefined"
      + "\nThe method or field ENDFORÂ is undefined"
      + "\nThe method or field def is undefined"
      + "\nThe method packages() is undefined"
      + "\nThe method or field def is undefined"
      + "\nThe method listings() is undefined"
      + "\nThe method or field def is undefined"
      + "\nThe method trueFalse() is undefined"
      + "\nThe method or field def is undefined"
      + "\nThe method choices() is undefined"
      + "\nType mismatch: cannot convert from Class<Question> to TextSegment"
      + "\nType mismatch: cannot convert from Class<TextSegment> to TextSegment"
      + "\nType mismatch: cannot convert from Class<OpenEnded> to TextSegment"
      + "\nType mismatch: cannot convert from Class<ClosedEnded> to TextSegment"
      + "\nType mismatch: cannot convert from Class<TrueFalse> to TextSegment"
      + "\nType mismatch: cannot convert from Class<CompoundQuestion> to TextSegment"
      + "\nUnreachable expression."
      + "\nThis expression is not allowed in this context, since it doesn\'t cause any side effects."
      + "\nstudentsÂ cannot be resolved"
      + "\nnameÂ cannot be resolved"
      + "\nTAÂ cannot be resolved"
      + "\nrender cannot be resolved"
      + "\nrender cannot be resolved"
      + "\nrender cannot be resolved"
      + "\nrender cannot be resolved"
      + "\nstyled cannot be resolved"
      + "\nsegments cannot be resolved"
      + "\nmap cannot be resolved"
      + "\njoin cannot be resolved"
      + "\ntext cannot be resolved"
      + "\nstyles cannot be resolved"
      + "\nstyles cannot be resolved"
      + "\ncontains cannot be resolved"
      + "\nescapedÂ cannot be resolved"
      + "\nscapedInlineÂ cannot be resolved"
      + "\nescapedÂ cannot be resolved"
      + "\nescaped cannot be resolved"
      + "\nescapedÂ cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\ntoString cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\nreplace cannot be resolved"
      + "\n! cannot be resolved"
      + "\npointsÂ cannot be resolved"
      + "\nstatement cannot be resolved"
      + "\nrenderÂ cannot be resolved"
      + "\nanswer cannot be resolved"
      + "\nrenderÂ cannot be resolved"
      + "\nexpectedLengthÂ cannot be resolved"
      + "\n! cannot be resolved"
      + "\npointsÂ cannot be resolved"
      + "\nstatement cannot be resolved"
      + "\nrenderÂ cannot be resolved"
      + "\noptionsÂ cannot be resolved"
      + "\nanswerÂ cannot be resolved"
      + "\nstatement cannot be resolved"
      + "\nrenderÂ cannot be resolved"
      + "\n! cannot be resolved"
      + "\npointsÂ cannot be resolved"
      + "\nanswerÂ cannot be resolved"
      + "\nstatement cannot be resolved"
      + "\nrenderÂ cannot be resolved"
      + "\npointsÂ cannot be resolved"
      + "\nstatement cannot be resolved"
      + "\nrenderÂ cannot be resolved"
      + "\nchildren cannot be resolved"
      + "\npointsÂ cannot be resolved"
      + "\nrender cannot be resolved"
      + "\nrender cannot be resolved"
      + "\nrender cannot be resolved");
  }
}
